### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by hkbase** [zz090923610/thunder-fastNiao#2]
Sun Jan 31 15:32:22 2016 daemon.info procd: Instance odhcpd::instance1 s in a crash loop 6 crashes, 0 seconds since last crash
Sun Jan 31 15:32:33 2016 kern.notice kernel: [   55.310000] random: nonblocking pool is initialized
Sun Jan 31 15:32:33 2016 daemon.err fastdick[1482]: ash: bad number
Sun Jan 31 15:32:33 2016 daemon.err fastdick[1482]: root: Thunder FastNiao Login Failed, sessionID should be 32 chars, dump response json and exit
Sun Jan 31 15:32:33 2016 user.notice root: Thunder FastNiao Login Failed, sessionID should be 32 chars, dump response json and exit
Sun Jan 31 15:32:33 2016 daemon.err fastdick[1482]: root: Thunder FastNiao <html>
Sun Jan 31 15:32:33 2016 daemon.err fastdick[1482]: <head><title>500 Internal Server Error</title></head>
Sun Jan 31 15:32:33 2016 daemon.err fastdick[1482]: <body bgcolor="white">
Sun Jan 31 15:32:33 2016 daemon.err fastdick[1482]: <center><h1>500 Internal Server Error</h1></center>
Sun Jan 31 15:32:33 2016 daemon.err fastdick[1482]: <hr><center>nginx/1.2.2</center>
Sun Jan 31 15:32:33 2016 daemon.err fastdick[1482]: </body>
Sun Jan 31 15:32:33 2016 daemon.err fastdick[1482]: </html>
Sun Jan 31 15:32:33 2016 user.notice root: Thunder FastNiao <html>
<head><title>500 Internal Server Error</title></head>
<body bgcolor="white">
<center><h1>500 Internal Server Error</h1></center>
<hr><center>nginx/1.2.2</center>
</body>
</html>
Sun Jan 31 16:02:13 2016 daemon.err fastdick[1864]: root: Thunder FastNiao Generating passwd md5
Sun Jan 31 16:02:13 2016 user.notice root: Thunder FastNiao Generating passwd md5
Sun Jan 31 16:02:13 2016 daemon.err fastdick[1864]: root: Thunder FastNiao Generating PWD RSA HEX
Sun Jan 31 16:02:13 2016 user.notice root: Thunder FastNiao Generating PWD RSA HEX
Sun Jan 31 16:02:14 2016 daemon.err fastdick[1864]: uci: Entry not found
Sun Jan 31 16:02:14 2016 daemon.err fastdick[1864]: ifconfig: : error fetching interface information: Device not found
Sun Jan 31 16:02:14 2016 daemon.err fastdick[1864]: root: Thunder FastNiao Trying login
Sun Jan 31 16:02:14 2016 user.notice root: Thunder FastNiao Trying login
Sun Jan 31 16:02:14 2016 daemon.err fastdick[1864]: ash: bad number
Sun Jan 31 16:02:14 2016 daemon.err fastdick[1864]: root: Thunder FastNiao Login Failed, sessionID should be 32 chars, dump response json and exit
Sun Jan 31 16:02:14 2016 user.notice root: Thunder FastNiao Login Failed, sessionID should be 32 chars, dump response json and exit
Sun Jan 31 16:02:14 2016 daemon.err fastdick[1864]: root: Thunder FastNiao <html>
Sun Jan 31 16:02:14 2016 daemon.err fastdick[1864]: <head><title>500 Internal Server Error</title></head>
Sun Jan 31 16:02:14 2016 daemon.err fastdick[1864]: <body bgcolor="white">
Sun Jan 31 16:02:14 2016 daemon.err fastdick[1864]: <center><h1>500 Internal Server Error</h1></center>
Sun Jan 31 16:02:14 2016 daemon.err fastdick[1864]: <hr><center>nginx/1.2.2</center>
Sun Jan 31 16:02:14 2016 daemon.err fastdick[1864]: </body>
Sun Jan 31 16:02:14 2016 daemon.err fastdick[1864]: </html>
Sun Jan 31 16:02:14 2016 user.notice root: Thunder FastNiao <html>
<head><title>500 Internal Server Error</title></head>
<body bgcolor="white">
<center><h1>500 Internal Server Error</h1></center>
<hr><center>nginx/1.2.2</center>
</body>
</html>

**Comment by hkbase** [comment]
固件版本    OpenWrt Chaos Calmer 15.05 / LuCI (git-15.248.30277-3836b45)
内核版本    3.18.20

官方ar71xx原版固件

用ifconfig命令查看我的互联网出口的接口名称叫 wlan0

**Comment by hkbase** [comment]
`root@OpenWrt:~# fastdick wlan0
root: Thunder FastNiao Generating passwd md5
root: Thunder FastNiao Generating PWD RSA HEX
uci: Entry not found
ifconfig: : error fetching interface information: Device not found
root: Thunder FastNiao Trying login
ash: bad number
root: Thunder FastNiao Login Failed, sessionID should be 32 chars, dump response json and exit
root: Thunder FastNiao <html>
<head><title>500 Internal Server Error</title></head>
<body bgcolor="white">
<center><h1>500 Internal Server Error</h1></center>
<hr><center>nginx/1.2.2</center>
</body>
</html>
`

**Comment by zz090923610** [comment]
@hkbase 看起来像是没有获取到一个合适的WAN口的MAC地址。。。。能贴个`ifconfig`的全部信息和`cat /etc/config/network`还有`cat /var/state/network`的信息吗，在这些信息里面你把你的账号密码啥的删掉我看看，应该是获取MAC地址出了问题。。。

**Comment by zz090923610** [comment]
@hkbase 试试最新版。。。如果获取不到 MAC 地址默认给了个 00:11:22:33:44:55，理论上讲应该不会登录失败

**Comment by hkbase** [comment]
root@OpenWrt:~# ifconfig
br-lan    Link encap:Ethernet  HWaddr 40:16:9F:6E:88:87
          inet addr:192.168.2.1  Bcast:192.168.2.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1480  Metric:1
          RX packets:2562825 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1875098 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:2156841712 (2.0 GiB)  TX bytes:1852805041 (1.7 GiB)

eth0      Link encap:Ethernet  HWaddr 40:16:9F:6E:88:87
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:2523941 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1839709 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:2176526921 (2.0 GiB)  TX bytes:1826358421 (1.7 GiB)
          Interrupt:5

eth1      Link encap:Ethernet  HWaddr 40:16:9F:6E:88:89
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
          Interrupt:4

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:103 errors:0 dropped:0 overruns:0 frame:0
          TX packets:103 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:9154 (8.9 KiB)  TX bytes:9154 (8.9 KiB)

wlan0     Link encap:Ethernet  HWaddr 40:16:9F:6E:88:88
          inet addr:192.168.1.99  Bcast:192.168.1.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1480  Metric:1
          RX packets:1911314 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2578341 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1898271700 (1.7 GiB)  TX bytes:2248193887 (2.0 GiB)

wlan0-1   Link encap:Ethernet  HWaddr 42:16:9F:6E:88:88
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:64695 errors:0 dropped:0 overruns:0 frame:0
          TX packets:78395 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:21549482 (20.5 MiB)  TX bytes:74158309 (70.7 MiB)

**Comment by hkbase** [comment]
root@OpenWrt:~# cat /etc/config/network

config interface 'loopback'
        option ifname 'lo'
        option proto 'static'
        option ipaddr '127.0.0.1'
        option netmask '255.0.0.0'

config globals 'globals'

config interface 'lan'
        option ifname 'eth0'
        option force_link '1'
        option type 'bridge'
        option proto 'static'
        option netmask '255.255.255.0'
        option mtu '1480'
        option ipaddr '192.168.2.1'

config interface 'wan'
        option ifname 'eth1'
        option proto 'dhcp'

config switch
        option name 'switch0'
        option reset '1'
        option enable_vlan '1'

config switch_vlan
        option device 'switch0'
        option vlan '1'
        option ports '0 1 2 3 4'

config interface 'wwan'
        option _orig_ifname 'wlan0'
        option _orig_bridge 'false'
        option proto 'static'
        option ipaddr '192.168.1.99'
        option netmask '255.255.255.0'
        option gateway '192.168.1.1'
        option dns '119.29.29.29'
        option mtu '1480'

**Comment by hkbase** [comment]
root@OpenWrt:~# cat /var/state/network
network.loopback.up='1'
network.loopback.device='lo'
network.wwan.up='1'
network.wwan.ifname='wlan0'
network.lan.up='1'
network.lan.device='eth0'
network.lan.ifname='br-lan'

**Comment by zz090923610** [comment]
懂了。。。你这是无线转有线是吧？我改改。。

**Comment by hkbase** [comment]
使用原作者的那个python版，是可以正常加速的，如下：
root@OpenWrt:~# python ./swjsq.py
Warning: pycrypto not found, use pure-python implemention
Login xunlei succeeded
To Upgrade: 陕西电信 Down 8M -> 20M, Up 1M -> 20M
Initializing upgrade
Upgrade done: Down 30M, Up 0M

**Comment by hkbase** [comment]
嗯，用的无线client+AP模式~~

**Comment by zz090923610** [comment]
@hkbase 感觉应该是MAC没取对，你先试试我最新提的那个版本。。我再针对改一下。

**Comment by hkbase** [comment]
刚用最新的版本，出错日志如下：
Sun Jan 31 21:17:04 2016 user.notice root: Thunder FastNiao Generating passwd md5
Sun Jan 31 21:17:04 2016 user.notice root: Thunder FastNiao Generating PWD RSA HEX
Sun Jan 31 21:17:04 2016 user.notice root: Thunder FastNiao Trying login
Sun Jan 31 21:17:05 2016 user.notice root: Thunder FastNiao Login Failed, sessionID should be 32 chars, dump response json and exit
Sun Jan 31 21:17:05 2016 user.notice root: Thunder FastNiao <html>
<head><title>500 Internal Server Error</title></head>
<body bgcolor="white">
<center><h1>500 Internal Server Error</h1></center>
<hr><center>nginx/1.2.2</center>
</body>
</html>

**Comment by zz090923610** [comment]
@hkbase openssl 装好了吗？

**Comment by hkbase** [comment]
root@OpenWrt:~# opkg install openssl-util
Package openssl-util (1.0.2f-1) installed in root is up to date.

**Comment by hkbase** [comment]
root@OpenWrt:~# opkg list-installed
base-files - 157-r46767
busybox - 1.23.2-1
curl - 7.40.0-3
dnsmasq - 2.73-1
dropbear - 2015.67-1
firewall - 2015-07-27
fstools - 2015-05-24-09027fc86babc3986027a0e677aca1b6999a9e14
hostapd-common - 2015-03-25-1
ip - 4.0.0-1
iptables - 1.4.21-1
iptables-mod-conntrack-extra - 1.4.21-1
iptables-mod-ipopt - 1.4.21-1
iw - 3.17-1
jshn - 2015-06-14-d1c66ef1131d14f0ed197b368d03f71b964e45f8
jsonfilter - 2014-06-19-cdc760c58077f44fc40adbbe41e1556a67c1b9a9
kernel - 3.18.20-1-7bed08fa9c06eb8089e82c200340ec66
kmod-ath - 3.18.20+2015-03-09-3
kmod-ath9k - 3.18.20+2015-03-09-3
kmod-ath9k-common - 3.18.20+2015-03-09-3
kmod-cfg80211 - 3.18.20+2015-03-09-3
kmod-crypto-aes - 3.18.20-1
kmod-crypto-arc4 - 3.18.20-1
kmod-crypto-core - 3.18.20-1
kmod-gpio-button-hotplug - 3.18.20-1
kmod-ifb - 3.18.20-1
kmod-ipt-conntrack - 3.18.20-1
kmod-ipt-conntrack-extra - 3.18.20-1
kmod-ipt-core - 3.18.20-1
kmod-ipt-ipopt - 3.18.20-1
kmod-ipt-nat - 3.18.20-1
kmod-ledtrig-usbdev - 3.18.20-1
kmod-lib-crc-ccitt - 3.18.20-1
kmod-mac80211 - 3.18.20+2015-03-09-3
kmod-nf-conntrack - 3.18.20-1
kmod-nf-ipt - 3.18.20-1
kmod-nf-nat - 3.18.20-1
kmod-nf-nathelper - 3.18.20-1
kmod-nls-base - 3.18.20-1
kmod-ppp - 3.18.20-1
kmod-pppoe - 3.18.20-1
kmod-pppox - 3.18.20-1
kmod-sched - 3.18.20-1
kmod-sched-core - 3.18.20-1
kmod-slhc - 3.18.20-1
kmod-usb-core - 3.18.20-1
kmod-usb2 - 3.18.20-1
libblobmsg-json - 2015-06-14-d1c66ef1131d14f0ed197b368d03f71b964e45f8
libbz2 - 1.0.6-2
libc - 0.9.33.2-1
libcurl - 7.40.0-3
libdb47 - 4.7.25.4.NC-4.1
libffi - 3.0.13-1
libgcc - 4.8-linaro-1
libgdbm - 1.11-1
libip4tc - 1.4.21-1
libip6tc - 1.4.21-1
libiwinfo - 2015-06-01-ade8b1b299cbd5748db1acf80dd3e9f567938371
libiwinfo-lua - 2015-06-01-ade8b1b299cbd5748db1acf80dd3e9f567938371
libjson-c - 0.12-1
libjson-script - 2015-06-14-d1c66ef1131d14f0ed197b368d03f71b964e45f8
liblua - 5.1.5-1
libncurses - 5.9-2
libnl-tiny - 0.1-4
libopenssl - 1.0.2f-1
libpcre - 8.38-1
libpolarssl - 1.3.14-1
libpthread - 0.9.33.2-1
librt - 0.9.33.2-1
libsqlite3 - 3081101-1
libubox - 2015-06-14-d1c66ef1131d14f0ed197b368d03f71b964e45f8
libubus - 2015-05-25-f361bfa5fcb2daadf3b160583ce665024f8d108e
libubus-lua - 2015-05-25-f361bfa5fcb2daadf3b160583ce665024f8d108e
libuci - 2015-04-09.1-1
libuci-lua - 2015-04-09.1-1
libxml2 - 2.9.2-3
libxtables - 1.4.21-1
lua - 5.1.5-1
luci - git-15.248.30277-3836b45-1
luci-app-firewall - git-15.248.30277-3836b45-1
luci-app-sqm - 1.0.3-1
luci-app-vlmcsd - svn812-2015-08-30
luci-base - git-15.248.30277-3836b45-1
luci-i18n-base-zh-cn - git-15.248.30277-3836b45-1
luci-lib-ip - git-15.248.30277-3836b45-1
luci-lib-nixio - git-15.248.30277-3836b45-1
luci-mod-admin-full - git-15.248.30277-3836b45-1
luci-proto-ipv6 - git-15.248.30277-3836b45-1
luci-proto-ppp - git-15.248.30277-3836b45-1
luci-theme-bootstrap - git-15.248.30277-3836b45-1
mtd - 21
netifd - 2015-06-08-8795f9ef89626cd658f615c78c6a17e990c0dcaa
odhcpd - 2015-05-21-2ebf6c8216287983779c8ec6597d30893b914a7c
openssl-util - 1.0.2f-1
opkg - 9c97d5ecd795709c8584e972bfdf3aee3a5b846d-7
ppp - 2.4.7-6
ppp-mod-pppoe - 2.4.7-6
procd - 2015-08-16-0da5bf2ff222d1a499172a6e09507388676b5a08
python - 2.7.9-5
python-base - 2.7.9-5
python-codecs - 2.7.9-5
python-compiler - 2.7.9-5
python-ctypes - 2.7.9-5
python-db - 2.7.9-5
python-decimal - 2.7.9-5
python-distutils - 2.7.9-5
python-email - 2.7.9-5
python-gdbm - 2.7.9-5
python-light - 2.7.9-5
python-logging - 2.7.9-5
python-multiprocessing - 2.7.9-5
python-ncurses - 2.7.9-5
python-openssl - 2.7.9-5
python-pydoc - 2.7.9-5
python-sqlite3 - 2.7.9-5
python-unittest - 2.7.9-5
python-xml - 2.7.9-5
rpcd - 2015-05-17-3d655417ab44d93aad56a6d4a668daf24b127b84
screen - 4.3.1-1
sqm-scripts - 1.0.3-1
swconfig - 10
swjsq - 0.0.1
tc - 4.0.0-1
terminfo - 5.9-2
thunder-fastdick - 0.6-0
uboot-envtools - 2014.10-2
ubox - 2015-07-14-907d046c8929fb74e5a3502a9498198695e62ad8
ubus - 2015-05-25-f361bfa5fcb2daadf3b160583ce665024f8d108e
ubusd - 2015-05-25-f361bfa5fcb2daadf3b160583ce665024f8d108e
uci - 2015-04-09.1-1
uhttpd - 2015-08-17-f91788b809d9726126e9cf4384fedbbb0c5b8a73
uhttpd-mod-ubus - 2015-08-17-f91788b809d9726126e9cf4384fedbbb0c5b8a73
usign - 2015-05-08-cf8dcdb8a4e874c77f3e9a8e9b643e8c17b19131
wget - 1.16.3-1
wpad-mini - 2015-03-25-1
zlib - 1.2.8-1

**Comment by zz090923610** [comment]
@hkbase 看起来登陆的返回值没问题。。。可能是咱们两省的sessionID长度不一样。。我新改了个版本你试试。。

**Comment by hkbase** [comment]
Sun Jan 31 21:35:19 2016 user.notice root: Thunder FastNiao Generating passwd md5
Sun Jan 31 21:35:19 2016 user.notice root: Thunder FastNiao Generating PWD RSA HEX
Sun Jan 31 21:35:19 2016 user.notice root: Thunder FastNiao Trying login
Sun Jan 31 21:35:20 2016 user.notice root: Thunder FastNiao Login Success
Sun Jan 31 21:35:20 2016 user.notice root: Thunder FastNiao You are a VIP, now preparing speedup
Sun Jan 31 21:35:20 2016 user.notice root: Thunder FastNiao Fetching Server Info
Sun Jan 31 21:35:20 2016 user.notice root: Thunder FastNiao Performing-bandwidth-action
Sun Jan 31 21:35:23 2016 user.notice root: Thunder FastNiao Performing-upgrade-action
Sun Jan 31 21:35:23 2016 user.notice root: Thunder FastNiao Speedup failed, dump response json and exit
Sun Jan 31 21:35:23 2016 user.notice root: Thunder FastNiao {"bandwidth":{"downstream":0,"upstream":0},"dial_account":"","errno":717,"message":"account auth session failed result:402","province":"shan_xi","province_name":"陕西","richmessage":"抱歉，您的账号登录状态异常，请重新登录","sequence":0,"sp":"tel","sp_name":"电信","timestamp":1454247322}
Sun Jan 31 21:35:35 2016 user.notice root: Thunder FastNiao Generating passwd md5
Sun Jan 31 21:35:35 2016 user.notice root: Thunder FastNiao Generating PWD RSA HEX
Sun Jan 31 21:35:35 2016 user.notice root: Thunder FastNiao Trying login
Sun Jan 31 21:35:36 2016 user.notice root: Thunder FastNiao Login Success
Sun Jan 31 21:35:36 2016 user.notice root: Thunder FastNiao You are a VIP, now preparing speedup
Sun Jan 31 21:35:36 2016 user.notice root: Thunder FastNiao Fetching Server Info
Sun Jan 31 21:35:36 2016 user.notice root: Thunder FastNiao Performing-bandwidth-action
Sun Jan 31 21:35:38 2016 user.notice root: Thunder FastNiao Performing-upgrade-action

**Comment by hkbase** [comment]
这个算是成功了，还是失败了？？？？

**Comment by zz090923610** [comment]
@hkbase 登陆异常。。你先试试 `/etc/init.d/fastdick stop` 然后确定python版本的那个也停了，然后 `/etc/init.d/fastdick start` 试试能不能不出错误log。

如果这次没成功，看起来还是sessionID有问题， 你把 /usr/bin/fastdick 用编辑器打开，在第一行末尾加上 -x，然后直接输入 fastdick 前台运行，把所有信息里删掉用户名和密码贴一下看看？

**Comment by hkbase** [comment]
root@OpenWrt:~# /etc/init.d/fastdick stop
Command failed: Not found
root@OpenWrt:~# /etc/init.d/fastdick start
root@OpenWrt:~#
运行之后，查看系统日志，啥信息都没有了

**Comment by zz090923610** [comment]
@hkbase 镱。。。要不开qq远程我debug一轮。。。

**Comment by hkbase** [comment]
好啊

**Comment by hkbase** [comment]
qq 20853790

**Comment by zz090923610** [comment]
@hkbase 我发加好友申请了。。。

**Comment by zz090923610** [comment]
是rsa取值的一个问题，应该已经修复了，可以测试下
