### ISSUE TITLE
Speedup failed, dump response json and exit 30/3

### ISSUE THREAD

**Issue by yezz5** [zz090923610/thunder-fastNiao#5]
{"bandwidth":{"downstream":0,"upstream":0},"dial_account":"","errno":717,"message":"account auth session failed result:402","province":"zhe_jiang","province_name":"浙江","richmessage":"抱歉，您的账号登录状态异常，请重新登录","sequence":0,"sp":"tel","sp_name":"电信","timestamp":1459341441}

3月30日开始出现的问题，能登录却不能加速

**Comment by zz090923610** [comment]
试试新版。
